---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: test-quota
  namespace: test-env
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "12"
    limits.memory: 24Gi
    pods: "20"
    services: "10"
    persistentvolumeclaims: "5"
