name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: node-k8s-app
  REGISTRY: docker.io
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Deploy to Minikube (via SSH or kubectl)
        run: |
          echo "Deploying to Kubernetes..."
          # Здесь вы можете использовать kubectl через SSH или использовать агент
          # Пример: если у вас есть доступ к кластеру
          # scp k8s/* user@minikube-server:/tmp/
          # ssh user@minikube-server "kubectl apply -f /tmp/"
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}  # base64-encoded kubeconfig
